name: yumzapp
description: Orbitals project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_sticky_header: ^0.4.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+1
  modal_progress_hud: ^0.1.3
  flutter_rating_bar: ^3.0.1+1
  flutter_tags: ^0.4.8+2




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Playball
      fonts:
        - asset: fonts/Playball-Regular.ttf
